# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Manohar Madhira
tagline: Musings of a Jack of many, master of some
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://rmadhira86.github.io" # the base hostname & protocol for your site, e.g. http://example.com

logo: /assets/img/logo.png
copyright: Manohar Madhira
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts / musings of a Jack of many, master of some. Here you will find 
  my thoughts and learning on various fields of life - 
  business operations, health, technology, relations and many more. 
  Come delve in a little, share your thoughts and let us grow together.  

author: manohar

social:
  links:
    - label: Github
      class: github
      icon: bi bi-github
      url: https://github.com/rmadhira86/
    - label: Linked-In
      class: linkedin
      icon: bi bi-linkedin
      url: https://www.linkedin.com/in/manohar-madhira/
    # - label: Twitter
    #   class: twitter
    #   icon: bi bi-twitter
    #   url: https://twitter.com/WatDaDuck_
    # - label: Facebook
    #   class: facebook
    #   icon: bi bi-facebook
    #   url: https://www.facebook.com/DonaldDuck/
    # - label: Instagram
    #   class: instagram
    #   icon: bi bi-instagram
    #   url: https://www.instagram.com/donaldduckweekblad/

      

permalink: none 

limits:
   related: 5
   latest: 5
   tag_match: 2

# Conversion
markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: rouge
lsi: false
excerpt_separator: "<!--more-->"
incremental: false

# Build settings
plugins:
  - jekyll-feed

# Build config 
sass:
  sass_dir: assets/css      #Folder where Syntactically Awesome StyleSheet files are located
  style: compressed

include:
  - _pages
     
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
